### ISSUE TITLE
No battery status returned

### ISSUE THREAD

**Issue by maximdim** [Canyoneer/ValenceRT-DecodingTool#1]
Thank you for making this available!

I tried it on my U1-12RT battery (single one), when it was discharging and below is the output. It seems that some communication with battery is happening, but battery data is not returned. I'm a bit confused also why there are two ids assigned to the single battery (2,3) - or is it normal? Would appreciate any feedback.

```
-> ff4306064246ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
<- ff70114342423132333230303031310d00
->  ff411243424231313238313030313102ccfe  # received battery id 303131 assigning bus id 2
 # response of set active bat id
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> ff4306064246ff4306064246
-> ff5006003381
<- ff70114342423132333230303031310d00
->  ff4112434242313132383130303131030d3e  # received battery id 303131 assigning bus id 3
 # response of set active bat id
-> ff500601f241
-> ff500602b240
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> 02030029001bd43a # request data from bus id 2
<-  # battery data
-> 03030029001bd5eb # request data from bus id 3
<-  # battery data
```

**Comment by Canyoneer** [comment]
The tool is requesting battery battery ids for some time and assignes bus ids to every battery id it receives without checking for duplicates. This never happened with my batteries, so I didn't know this could happen. I will fix this in about 10 days when I have access to my development machine again.

**Comment by Canyoneer** [comment]
Thanks for the pull request! Did it fix the problem?

I'm afraid that it might not. The root cause could be that the message to set the bus id is send to soon and the wait time for the response is too short. So I added explicit waits to roughly match the displays timing.

**Comment by maximdim** [comment]
It only fixed the problem of battery being identified twice. Still can't get no battery info.

Thanks for the tip on timing. I will give it a try and let you know.

**Comment by HexNoob2** [comment]
I am having same issue as maximdim.  There is communication, duplicate ID with a single battery, and no battery info.


```
-> ff4306064246ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
<- ff70114342423131323230303539360bd6
->  ff4112434242313132383130353936024fc0  # received battery id 353936 assigning bus id 2
 # response of set active bat id
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> ff4306064246ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
-> ff5006037380
-> ff5006043242
<- ff70114342423131323230303539360bd6
skipping duplicate id  353936
-> ff500605f382
-> 02030029001bd43a # request data from bus id 2
<-  # battery data

```

**Comment by Canyoneer** [comment]
Sorry that I couldn't answer earlier. I thought that I had pushed the timing changes to the repository 3 years ago, but I didn't. 

I did this some minutes ago and hope that it will fix the problem. In the logs above there should be a message starting with ff42 in the " # response of set active bat id" line. I couldn't reproduce the problem with the new version and my batteries.

**Comment by HexNoob2** [comment]
EDIT: I am now realizing that this RT battery was used with a Tripp-Lite HC150SL UPS, I have it connected and it is charging the battery now.  It has kicked on a fan which I assume means fast charge mode.

I am trying to capture some of the communication, but I am not getting a clean capture with "Teyleten Robot USB to RS485 Converter Adapter CH340T" and "Free Device Monitoring Studio" software set to listen mode.  Any pointers and I will try to get a good capture.

```
 fb fb bfm b2 d6 92 d2 b6k b2m b2 d6 b2m 92 b2m b2I b2I
 92 b2m 92 b2M b2I b2I b2I2H 922H 12"H"H"H"H H 02 00 12 01 80  ff 00
 00u fa 01 03 00  f0 01 03 00 ff 00 00u fa 01 03 00 
 f0 01 03 00! 00 01 d4 00 01 03 02 a4 01 03D 01 03
 00/ 00 01 b5 c3 01 03 02 1e 1e1 ec 01 03 003 00 04
 b4 06 01 03 08 1a 01 00 00 1a 01 00 00R bc 01 03
 00= 00 01 15 c6 01 03 02 fe fey a4 01 03 00> 00 02
 a5 c7 01 03 04 00 10 04 00 f96 01 03 007 00 015
 c4 01 03 02 10tA 01 03 008

 00 01 05 c7 01 03 02} 11 01 03 009 00 02 14 06 01
 03 0464 00 00 b4u 01 03 00! 00 01 d4 00 01 03 02 a4
 01 03D 01 03 00/ 00 01 b5 c3 01 03 02 1e 1e1 ec 01
 03 003 00 04 b4 06 01 03 08U 01 00 00U 01 00 00 00
 18 01 03 00= 00 01 15 c6 01 03 02 fe fey a4 01 03
 00> 00 02 a5 c7 01 03 04 00 10 04 00 f96 01 03 007
 00 015
 c4 01 03 02 0e} e1 01 03 008
 00 01 05 c7 01 03 02 0c| 81 01 03 009 00 02 14 06
 01 03 0464 00 00 b4u 01 03 00! 00 01 d4 00 01 03 02
 a4 01 03D 01 03 00/ 00 01 b5 c3 01 83 02 c0 f1 01
 03 00/ 00 01 b5 c3 01 03 02 1e 1e1 ec 01 03 003 00
 04 b4 06 01 03 08 11 00 00 00 11 00 00 00P+ 01 03
 00= 00 01 15 c6 01 03 02 fe fey a4 01 03 00> 00 02
 a5 c7 01 03 04 00 08 04 00y1 01 03 007 00 015

```

Same results as before, I am not getting any ff42 responses at all.  I tried on 2 batteries, they must have a different message protocol than yours even though they say U1-12RT.

```
-> ff4306064246
-> ff4306064246
-> ff5006003381
-> ff500601f241
<- ff70114342423131323230303336346fe6
->  ff4112434242313132383130333634027e2b # received battery id 333634 assigning bus id 2
 # response of set active bat id
-> ff500602b240
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> ff4306064246
-> ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
-> ff5006037380
-> ff5006043242
<- ff70114342423131323230303336346fe6
skipping duplicate id  333634
-> ff500605f382
-> 02030029001bd43a # request data from bus id 2
<-  # battery data
```

**Comment by Canyoneer** [comment]
It is possible that they use a different protocol, but I think that it is more likely a problem with my code. Looking at the the logs it seems that my assumption that the battery id is 3 bytes long was wrong and worked for me because the ids of my batteries are quite similar.

I changed the code so now everything after "ff7011" and before the CRC is used as battery id. I hope this fixes the problem for you. 

I tried to validate this by sending the  ff70114342423131323230303336346fe6 message to a Valence UCharge display, but could't get this work in a reasonable amount of time.

**Comment by HexNoob2** [comment]
Much Success!  Thank you!  :D

```
-> ff4306064246
-> ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
<- ff70114342423131323230303539360bd6
->  ff411243424231313232303035393602e411 # received battery id 434242313132323030353936 assigning bus id 2
ff4206021245 # response of set active bat id
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> ff4306064246
-> ff4306064246
-> ff5006003381
-> ff500601f241
-> ff500602b240
-> ff5006037380
-> ff5006043242
-> ff500605f382
-> 02030029001bd43a # request data from bus id 2
<- 0203361c1b1d1c0f101150400800001b1d1b1b1b1b2100f0000000f0000000b20cab0cbc320000bc320000fafa00100400b00cab0caf0cb20c8528
SOC:  98.0392156862745 %
I1:  0.24 A
I2:  0.24 A (sometimes much (20-33%) lower then I1 and measured charging current.
Ubat:  12.988 V
P:  3.11712 W
U1:  3.248 V
U2:  3.243 V
U3:  3.247 V
U4:  3.25 V
U5:  3.25 V
U6:  3.243 V
T1:  28 C
T2:  29 C
T3 (PCB):  27 C
T4 (PCB):  27 C
T5:  27 C
T6:  28 C
```

**Comment by Canyoneer** [comment]
Thanks for the feedback!
